label {
	name: 'shape'

	item {
	  id: 1
	  name: 'rectangle'
	}

	item {
	  id: 2
	  name: 'circle'
	}

	item {
	  id: 3
	  name: 'triangle'
	}

	item {
	  id: 4
	  name: 'trapezoid'
	}

	item {
	  id: 5
	  name: 'pentagon'
	}

	item {
	  id: 6
	  name: 'hexagon'
	}

	item {
	  id: 7
	  name: 'semicircle'
	}

	item {
	  id: 8
	  name: 'square'
	}

	item {
	  id: 9
	  name: 'heptagon'
	}

	item {
	  id: 10
	  name: 'quartercircle'
	}

	item {
	  id: 11
	  name: 'star'
	}

	item {
	  id: 12
	  name: 'cross'
	}

	item {
	  id: 13
	  name: 'octagon'
	}

}

label {
	name: "rotation_angle"
	
	item {
	  id: 1,
	  name: 'N'
	}

	item {
	  id: 2,
	  name: 'NW'
	}

	item {
	  id: 3,
	  name: 'W'
	}

	item {
	  id: 4
	  name: 'SW'
	}

	item {
	  id: 5,
	  name: 'S'
	}

	item {
	  id: 6,
	  name: 'SE'
	}

        item {
	  id: 7,
	  name: 'E'
	
	}

	item {
	  id: 8,
	  name: 'NE'
	}
	
}

label {
	name: 'alphanumeric'

	item {
	  id: 1

	  name: '0'
	}

	item {
	  id: 2
	  name: '1'
	}

	item {
	  id: 3
	  name: '2'
	}

	item {
	  id: 4
	  name: '3'
	}

	item {
	  id: 5
	  name: '4'
	}

	item {
	  id: 6
	  name: '5'
	}

	item {
	  id: 7
	  name: '6'
	}

	item {
	  id: 8
	  name: '7'
	}

	item {
	  id: 9
	  name: '8'
	}

	item {
	  id: 10
	  name: '9'
	}
 
	item {
	  id: 11
	  name: 'A'
	}

	item {
	  id: 12
	  name: 'B'
	}

        item {
	  id: 13
	  name: 'C'
	}

        item {
	  id: 14
	  name: 'D'
	}

	item {
	  id: 15
	  name: 'E'
	}
	item {
	  id: 16
	  name: 'F'
	}
	item {
	  id: 17
	  name: 'G'
	}
	item {
	  id: 18
	  name: 'H'
	}
	item {
	  id: 19
	  name: 'I'
	}
	item {
	  id: 20
	  name: 'J'
	}
	item {
	  id: 21
	  name: 'K'
	}
	item {
	  id: 22
	  name: 'L'
	}
	item {
	  id: 23
	  name: 'M'
	}
	item {
	  id: 24
	  name: 'N'
	}
	item {
	  id: 25
	  name: 'O'
	}
	item {
	  id: 26
	  name: 'P'
	}
	item {
	  id: 27
	  name: 'Q'
	}
	item {
	  id: 28
	  name: 'R'
	}
	item {
	  id: 29
	  name: 'S'
	}
	item {
	  id: 30
	  name: 'T'
	}
	item {
	  id: 31
	  name: 'U'
	}
	item {
	  id: 32
	  name: 'V'
	}
	item {
	  id: 33
	  name: 'W'
	}
	item {
	  id: 34
	  name: 'X'
	}
	item {
	  id: 35
	  name: 'Y'
	}
	item {
	  id: 36
	  name: 'Z'
	}


}
