# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classification/protos/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='classification/protos/model.proto',
  package='',
  serialized_pb=_b('\n!classification/protos/model.proto\"\xa2\x01\n\x0eMultiTaskClass\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x03num\x18\x02 \x01(\x05:\x01\x30\x12\x16\n\x0bstarts_from\x18\x03 \x01(\x05:\x01\x31\x12\"\n\x0bloss_config\x18\x04 \x01(\t:\rcross_entropy\x12\x1a\n\x0chas_accuracy\x18\x05 \x01(\x08:\x04true\x12\x1a\n\x0c\x61pply_logits\x18\x06 \x01(\x08:\x04true\"E\n\x05Model\x12\x11\n\textractor\x18\x01 \x02(\t\x12)\n\x10multi_task_label\x18\x02 \x03(\x0b\x32\x0f.MultiTaskClass')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MULTITASKCLASS = _descriptor.Descriptor(
  name='MultiTaskClass',
  full_name='MultiTaskClass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MultiTaskClass.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='MultiTaskClass.num', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='starts_from', full_name='MultiTaskClass.starts_from', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loss_config', full_name='MultiTaskClass.loss_config', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("cross_entropy").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='has_accuracy', full_name='MultiTaskClass.has_accuracy', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='apply_logits', full_name='MultiTaskClass.apply_logits', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=200,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extractor', full_name='Model.extractor', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multi_task_label', full_name='Model.multi_task_label', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=271,
)

_MODEL.fields_by_name['multi_task_label'].message_type = _MULTITASKCLASS
DESCRIPTOR.message_types_by_name['MultiTaskClass'] = _MULTITASKCLASS
DESCRIPTOR.message_types_by_name['Model'] = _MODEL

MultiTaskClass = _reflection.GeneratedProtocolMessageType('MultiTaskClass', (_message.Message,), dict(
  DESCRIPTOR = _MULTITASKCLASS,
  __module__ = 'classification.protos.model_pb2'
  # @@protoc_insertion_point(class_scope:MultiTaskClass)
  ))
_sym_db.RegisterMessage(MultiTaskClass)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'classification.protos.model_pb2'
  # @@protoc_insertion_point(class_scope:Model)
  ))
_sym_db.RegisterMessage(Model)


# @@protoc_insertion_point(module_scope)
