# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classification/protos/model.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='classification/protos/model.proto',
  package='',
  serialized_pb=_b('\n!classification/protos/model.proto\"+\n\x0eMultiTaskClass\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0b\n\x03num\x18\x02 \x02(\x05\"E\n\x05Model\x12\x11\n\textractor\x18\x01 \x02(\t\x12)\n\x10multi_task_label\x18\x02 \x03(\x0b\x32\x0f.MultiTaskClass')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MULTITASKCLASS = _descriptor.Descriptor(
  name='MultiTaskClass',
  full_name='MultiTaskClass',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='MultiTaskClass.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='MultiTaskClass.num', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=80,
)


_MODEL = _descriptor.Descriptor(
  name='Model',
  full_name='Model',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='extractor', full_name='Model.extractor', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multi_task_label', full_name='Model.multi_task_label', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=151,
)

_MODEL.fields_by_name['multi_task_label'].message_type = _MULTITASKCLASS
DESCRIPTOR.message_types_by_name['MultiTaskClass'] = _MULTITASKCLASS
DESCRIPTOR.message_types_by_name['Model'] = _MODEL

MultiTaskClass = _reflection.GeneratedProtocolMessageType('MultiTaskClass', (_message.Message,), dict(
  DESCRIPTOR = _MULTITASKCLASS,
  __module__ = 'classification.protos.model_pb2'
  # @@protoc_insertion_point(class_scope:MultiTaskClass)
  ))
_sym_db.RegisterMessage(MultiTaskClass)

Model = _reflection.GeneratedProtocolMessageType('Model', (_message.Message,), dict(
  DESCRIPTOR = _MODEL,
  __module__ = 'classification.protos.model_pb2'
  # @@protoc_insertion_point(class_scope:Model)
  ))
_sym_db.RegisterMessage(Model)


# @@protoc_insertion_point(module_scope)
