# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: classification/protos/pipeline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import classification.protos.input_reader_pb2
import classification.protos.model_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='classification/protos/pipeline.proto',
  package='classification.protos',
  serialized_pb=_b('\n$classification/protos/pipeline.proto\x12\x15\x63lassification.protos\x1a(classification/protos/input_reader.proto\x1a!classification/protos/model.proto\"p\n\x17TrainEvalPipelineConfig\x12\x15\n\x05model\x18\x01 \x01(\x0b\x32\x06.Model\x12>\n\x12train_input_reader\x18\x02 \x01(\x0b\x32\".classification.protos.InputReader')
  ,
  dependencies=[classification.protos.input_reader_pb2.DESCRIPTOR,classification.protos.model_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRAINEVALPIPELINECONFIG = _descriptor.Descriptor(
  name='TrainEvalPipelineConfig',
  full_name='classification.protos.TrainEvalPipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='classification.protos.TrainEvalPipelineConfig.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_input_reader', full_name='classification.protos.TrainEvalPipelineConfig.train_input_reader', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=252,
)

_TRAINEVALPIPELINECONFIG.fields_by_name['model'].message_type = classification.protos.model_pb2._MODEL
_TRAINEVALPIPELINECONFIG.fields_by_name['train_input_reader'].message_type = classification.protos.input_reader_pb2._INPUTREADER
DESCRIPTOR.message_types_by_name['TrainEvalPipelineConfig'] = _TRAINEVALPIPELINECONFIG

TrainEvalPipelineConfig = _reflection.GeneratedProtocolMessageType('TrainEvalPipelineConfig', (_message.Message,), dict(
  DESCRIPTOR = _TRAINEVALPIPELINECONFIG,
  __module__ = 'classification.protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:classification.protos.TrainEvalPipelineConfig)
  ))
_sym_db.RegisterMessage(TrainEvalPipelineConfig)


# @@protoc_insertion_point(module_scope)
